[project]
name = "summarize"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ebooklib>=0.18",
    "google-genai>=1.11.0",
    "trafilatura>=1.12.2",
]
scripts = { "summarize" = "esum.__main__:main" }
